### ISSUE TITLE
Still can't run server.js

### ISSUE THREAD

**Issue by jedvillan** [ramyakandasamy7/cmpe272CerealKillers#5]
See log error:
```
ubuntu@ip-172-31-95-140:~/cmpe272CerealKillers/Expense$ nodemon server.js
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
todo list RESTful API server started on: 5000
(node:26550) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:26550) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Database is connected
(node:26550) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/home/ubuntu/cmpe272CerealKillers/Expense/node_modules/mongodb/lib/core/topologies/server.js:431:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at connect (/home/ubuntu/cmpe272CerealKillers/Expense/node_modules/mongodb/lib/core/connection/pool.js:580:14)
    at makeConnection (/home/ubuntu/cmpe272CerealKillers/Expense/node_modules/mongodb/lib/core/connection/connect.js:39:11)
    at callback (/home/ubuntu/cmpe272CerealKillers/Expense/node_modules/mongodb/lib/core/connection/connect.js:261:5)
    at Socket.err (/home/ubuntu/cmpe272CerealKillers/Expense/node_modules/mongodb/lib/core/connection/connect.js:286:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:26550) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26550) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Looks like its still trying to connect to some MongoDB?

**Comment by jedvillan** [comment]
Raymond fixed it! Yay!
